require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Layout/LineLength:
  Max: 120

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - '_'
    - 'q'
    - 'ip'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/CaseLikeIf:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false
